# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Loren Lee Chen
tagline:             'Data Scientist from Newton, MA'
description:         'Data Scientist from Newton, MA'
url:                 http://lorenlchen.github.io
baseurl:             ''
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# About/contact
author:
  name:              Loren Lee Chen
  url:               https://www.twitter.com/LorenLChen
  email:             lorenlchen@gmail.com

# Custom vars
version:             1.0.0
